services:
  laravel2:
    container_name: laravel2
    build:
      context: ./docker
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    networks:
      - web
    labels:
      - "traefik.enable=false"

  server2:
    image: nginx:alpine
    container_name: server2
    ports:
      - "8082:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.server2.rule=Host(`laravel2.home.com`)"
      - "traefik.http.routers.server2.entrypoints=https"
      - "traefik.http.routers.server2.tls=true"
      - "traefik.http.routers.server2.service=server2@docker"
      - "traefik.http.services.server2.loadbalancer.server.port=80"
    depends_on:
      - laravel2

networks:
  web:
    external: true
