services:
  laravel1:
    container_name: laravel1
    build:
      context: ./docker
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    networks:
      - web
    labels:
      - "traefik.enable=false"

  server1:
    image: nginx:alpine
    container_name: server1
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.server1.rule=Host(`laravel1.site.com`)"
      - "traefik.http.routers.server1.entrypoints=https"
      - "traefik.http.routers.server1.tls=true"
      - "traefik.http.routers.server1.service=server1@docker"
      - "traefik.http.services.server1.loadbalancer.server.port=80"
    depends_on:
      - laravel1

networks:
  web:
    external: true
