services:
  laravel4:
    container_name: laravel4
    build:
      context: ./docker
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    networks:
      - web
    labels:
      - "traefik.enable=false"

  server4:
    image: nginx:alpine
    container_name: server4
    ports:
      - "8084:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.server4.rule=Host(`laravel4.local.com`)"
      - "traefik.http.routers.server4.entrypoints=https"
      - "traefik.http.routers.server4.tls=true"
      - "traefik.http.routers.server4.service=server4@docker"
      - "traefik.http.services.server4.loadbalancer.server.port=80"
    depends_on:
      - laravel4

networks:
  web:
    external: true
